### ISSUE TITLE
Feature Request: Server Version with WebUI instead of Desktop UI

### ISSUE THREAD

**Issue by TailsxKyuubi** [BastianGanze/weebsync#2]
Like in the title said. it would be nice to have a server version/mode which hosts an administrative website, because in my case i need just for that a windows vm running and would like to do this with a freebsd jail

**Comment by BastianGanze** [comment]
I will do this. In the first iteration you'd just checkout the repository, install the dependencies and then run `npm run server-version` if that's okay for you.
