### ISSUE TITLE
http://0.0.0.0:42380 ist unter Windows nicht abrufbar

### ISSUE THREAD

**Issue by Ninelpienel** [BastianGanze/weebsync#5]
Wenn man die neuste Version von weebsync unter Windows ausführt, wird als Host-Link http://0.0.0.0:42380 angegeben. Jedoch kann man unter Windows nur mit http://localhost:42380 oder der entsprechenden PC-IP-Adresse connecten. Das sollte angepasst werden.

![image](https://github.com/BastianGanze/weebsync/assets/1890524/a8cfdc5f-6a7a-401d-9581-8aba060c630e)

**Comment by BastianGanze** [comment]
This works es designed. 0.0.0.0 is a wildcard for ALL ip addresses, you cannot connect directly to 0.0.0.0 but this way you can connec to the server through any ip adress that the host system corresponse to. If you wish to change the bound host please consult the README.md file.
https://stackoverflow.com/questions/68399706/client-program-cant-connect-to-server-hosted-on-0-0-0-0
